//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalContext
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalContext()
        {
            this.IsmsScopes = new HashSet<IsmsScope>();
        }
    
        public int externalContextId { get; set; }
        public string socialDes { get; set; }
        public string culturalDes { get; set; }
        public string politicalDes { get; set; }
        public string regulatoryDes { get; set; }
        public string legalDes { get; set; }
        public string financialDes { get; set; }
        public string technologicalDes { get; set; }
        public string naturalDes { get; set; }
        public string competitiveDes { get; set; }
        public string keyDriversDes { get; set; }
        public string externalStakeholdersDes { get; set; }
        public string contractualRelationshipsDes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsmsScope> IsmsScopes { get; set; }
    }
}
