//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsmsScope
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IsmsScope()
        {
            this.Departments = new HashSet<Department>();
            this.InterestedParties = new HashSet<InterestedParty>();
            this.InterfacesDependencies = new HashSet<InterfacesDependency>();
            this.Projects = new HashSet<Project>();
            this.Sites = new HashSet<Site>();
        }
    
        public int ismsId { get; set; }
        public string personalDes { get; set; }
        public string scopeExclusionsBoundaries { get; set; }
        public Nullable<int> internalContextId { get; set; }
        public Nullable<int> externalContextId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ExternalContext ExternalContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterestedParty> InterestedParties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterfacesDependency> InterfacesDependencies { get; set; }
        public virtual InternalContext InternalContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site> Sites { get; set; }
    }
}
